# Generated by Django 2.2.1 on 2022-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='admin')),
                ('password', models.TextField(default='pass')),
                ('name', models.TextField(default='Admin')),
                ('season', models.TextField(default='0.0')),
            ],
        ),
    ]
