# Generated by Django 2.2.1 on 2022-03-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0002_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('body', models.TextField(default='')),
                ('createdon', models.TextField(default='')),
                ('uniqueID', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MiniClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.TextField(default='')),
                ('createdon', models.TextField(default='')),
                ('userID', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MiniScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('scriptID', models.TextField(default='')),
                ('createdon', models.TextField(default='')),
                ('userID', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NotePad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('body', models.TextField(default='')),
                ('createdon', models.TextField(default='')),
                ('color', models.TextField(default='')),
                ('uniqueID', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.TextField(default='')),
                ('userID', models.TextField(default='')),
                ('amount', models.TextField(default='')),
                ('createdon', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('data', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='script',
            name='color',
            field=models.TextField(default=''),
        ),
    ]
