# Generated by Django 2.2.1 on 2022-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0003_auto_20220303_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniscript',
            name='color',
            field=models.TextField(default=''),
        ),
    ]
