# Generated by Django 2.2.1 on 2022-03-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0005_notepad_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.TextField(default='')),
                ('userID', models.TextField(default='')),
                ('amount', models.TextField(default='')),
                ('createdon', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('startingDate', models.TextField(default='')),
                ('endingDate', models.TextField(default='')),
                ('transactionID', models.TextField(default='')),
            ],
        ),
    ]
