# Generated by Django 2.2.1 on 2022-03-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='clientName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='clientName',
            field=models.TextField(default=''),
        ),
    ]
