# Generated by Django 2.2.1 on 2022-03-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0007_auto_20220314_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscriptionID',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='subscriptionMode',
            field=models.TextField(default=''),
        ),
    ]
