# Generated by Django 2.2.1 on 2022-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0009_audiostore_characterstore_structuresamplestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.TextField(default=''),
        ),
    ]
