# Generated by Django 2.2.2 on 2022-07-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0011_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstore',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
