# Generated by Django 2.2.2 on 2022-07-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0012_characterstore_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiostore',
            old_name='data',
            new_name='fileName',
        ),
    ]
