# Generated by Django 3.2.9 on 2022-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0014_alter_app_id_alter_audiostore_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.TextField(default='')),
                ('scriptID', models.TextField(default='')),
                ('sw_editor_id', models.TextField(default='')),
                ('userID', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('createdon', models.TextField(default='')),
            ],
        ),
    ]
