# Generated by Django 4.1.2 on 2022-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0016_client_authorreminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bg_color',
            field=models.TextField(default='yellow'),
        ),
    ]
